Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
websocket connection is closing.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 73, in on_message
    channel = message.author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_messagewebsocket connection is closing.

Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
Ignoring exception in on_message
Traceback (most recent call last):
  File "aingbot.py", line 76, in on_message
    vc = await channel.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 1097, in connect
    voice = VoiceClient(state=state, timeout=timeout, channel=self)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/voice_client.py", line 90, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "aingbot.py", line 83, in on_message
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
